services:
  laravel:
    build:
      context: .
      args:
        - PORT=8080
        - SSR=true
    env_file:
      - path: ./.env
        required: true
    ports:
      - "8080:8080"
  inertia-ssr:
    build:
      context: .
      args:
        - PORT=13714
    command: php artisan inertia:start-ssr
    ports:
      - "13714:13714"

